#FoosOBSPlus AutoScore Settings
#Sun Mar 22 21:25:54 CDT 2026
AutoScoreSettingsAutoConnect=0
AutoScoreSettingsDetailLog=1
AutoScoreSettingsServerAddress=192.168.68.79
AutoScoreSettingsServerPort=5050
