#FoosOBSPlus Control settings
#Sun Mar 15 21:04:13 CDT 2026
AnnounceMeatball=1
AnnounceWinner=1
AutoCapNames=1
AutoIncrementGame=1
BallsInRack=9
ClearLastScored=Last Scored
CutThroatMode=0
GameTime=90
GamesToWin=2
MaxTimeOuts=2
MaxWin=8
Meatball=Meatball\!\!\!
NameSeparator=/
PassTime=10
PointesToWin=51
PointsToWin=5
RackMode=0
RecallTime=10
ShotTime=15
ShowParsed=false
ShowSkunk=1
ShowTimeOutsUsed=0
Side1Color=Yellow
Side2Color=Black
Side3Color=Black
TableName=
Team1LastScored=<--- Last Scored
Team2LastScored=Last Scored --->
Team3LastScored=---> Team 3 <---
TimeOutTime=30
WinBy=1
WinByFinalOnly=1
WinnerPrefix=Match Winner\: 
WinnerSuffix=\!\!\!
datapath=c\:\\temp
